=== BananaMasta/LabaJava/JavaLaba/src/Laba/XML/Car.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT Carlist (carnumber*)>
        <!ELEMENT carnumber (car*, AmountOfPrice?)>
        <!ATTLIST carnumber
                number CDATA #REQUIRED
                >

        <!ELEMENT car (carprice, carstats)>
        <!ATTLIST car
                name CDATA #REQUIRED
                >

        <!ELEMENT carprice EMPTY>
        <!ATTLIST carprice
                price CDATA #REQUIRED
                >

        <!ELEMENT carstats EMPTY>
        <!ATTLIST carstats
                maxspeed CDATA #REQUIRED
                horsepower CDATA #REQUIRED
                >
        <!ELEMENT AmountOfPrice (#PCDATA)>

=== BananaMasta/LabaJava/JavaLaba/src/Laba/XML/Carlist.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Carlist SYSTEM "Car.dtd">
<Carlist>
    <carnumber number="0">
        <car name="Bugatti Divo">
            <carprice price="5400000"/>
            <carstats maxspeed="380" horsepower="1500" />
        </car>
        <car name="Bugatti Chiron">
            <carprice price="3000000"/>
            <carstats maxspeed="420" horsepower="1500" />
        </car>
        <car name="Bugatti La Voiture Noire">
            <carprice price="11000000"/>
            <carstats maxspeed="420" horsepower="1500" />
        </car>
    </carnumber>
</Carlist>
